- title: Writing
  icon: pencil
  text: "From notetaking and reports to strategic planning, let Pine Gum Studio help you articulate your vision and share your story."
- title: Facilitation and Convening
  icon: comment
  text: "If you are looking for a dynamic and engaging speaker, Pine Gum Studio can provide meeting facilitation, keynote speaking, as well as event hosting or emceeing."
- title: Creative Collaborations
  icon: heart
  text: "Working in partnership is the heart of Pine Gum Studio. Whether you are planning an exciting event or executing your dream project, we will work with you to bring together the right people and resources to bring it to life."
